SinkVim.keymap("n", "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", "Toggle pin")
SinkVim.keymap("n", "<leader>bP", "<Cmd>BufferLineGroupClose ungrouped<CR>", "Delete non-pinned buffers")
SinkVim.keymap("n", "H", "<Cmd>BufferLineCyclePrev<CR>", "Prev Buffer")
SinkVim.keymap("n", "L", "<Cmd>BufferLineCycleNext<CR>", "Next Buffer")
SinkVim.keymap("n", "<leader>bl", "<Cmd>BufferLineCloseRight<CR>", "Delete Buffers to the Right")
SinkVim.keymap("n", "<leader>bh", "<Cmd>BufferLineCloseLeft<CR>", "Delete Buffers to the Left")
SinkVim.keymap("n", "<leader>bo", "<Cmd>BufferLineCloseOthers<CR>", "Delete Other Buffers")
SinkVim.keymap("n", "[B", "<Cmd>BufferLineMovePrev<CR>", "Move buffer prev")
SinkVim.keymap("n", "]B", "<Cmd>BufferLineMoveNext<CR>", "Move buffer next")
